### ISSUE TITLE
UserBalance linking to user.level

### ISSUE THREAD

**Issue by brandonbothell** [NatsukiBot/db#15]
https://github.com/NightwatchBot/db/blob/79224bbb9ded1aaecce1c29f2be82b8618a1bb69/src/entity/User/UserBalance.ts#L16

Shouldn't this line be `@OneToOne(type => User, user => user.balance)`?

**Comment by tgoins** [comment]
Yes, nice catch.

**Comment by tgoins** [comment]
Fixed in latest v0.9.5
