### ISSUE TITLE
Determine what shop tables are needed.

### ISSUE THREAD

**Issue by tgoins** [NatsukiBot/db#24]
How do we store the sellable items?

How to we keep track of what items a user has purchased?

What types of items will be sold?

How do we organize/categorize the different types of items?

**Comment by brandonbothell** [comment]
We would probably need something like this:

* Shop
	* `@OneToMany` categories: ShopCategory[]
	* id: number
	* name: string
	* description: string
* Category
	* id: number
	* `@OneToMany` items: ShopItem[]
	* name: string
	* description: string
	* `@ManyToOne` shop: Shop
* ShopItem
	* id: number
	* name: string
	* description: string
	* price: number
	* `@ManyToMany` purchasers: User[]
	* `@ManyToOne` category: Category
* User
	* `@ManyToMany` purchases: ShopItem[]

Beware, I kinda just wrote this out and it may not be the best system. 
Edit: Might be better to create a `Purchase` type, and have users have those. /shrug

**Comment by tgoins** [comment]
We'd also need a way (table) to track what the user owns.

I was thinking the table would be called "UserInventoryItem" and the user table would have a property `inventory`, which is of type `UserInventoryItem[]`

Off the top of my head, it would need at least these columns:

 * datePurchased or timestamp - The date the item was purchased
 * item - The item that was purchased
 * user - The user that purchased the item

**Comment by tgoins** [comment]
Let me kinda clarify the category stuff:

The shop may sell these items: Profile Background, Level Background, Badge, etc.

These may be considered categories, but things like Profile Backgrounds and Level Backgrounds will have their own categories, like Anime, Abstract, Animals, Nature, Music, Games, Sports, etc.

And for badges (which I guess could also have their own categories, the same as the backgrounds), we would need to store where on the profile the badges are located.

A shop item may be a profile background. That same item can't also be a level background. This would be a one to many.

A profile background though may have many categories (maybe call them tags?), like can categorized as Anime and Animal.

**Comment by brandonbothell** [comment]
So maybe something like this? 

* Shop
	* id: number
	* name: string
	* description: string
    * `@ManyToMany` itemTypes: ShopItemType[]

* ShopItemType
    * id: number
    * name: string
    * description: string
    * `@ManyToMany` shops: Shop[]
    * `@OneToMany` items: ShopItem[]

* ShopItemTag
	* id: number
	* name: string
	* description: string
    * `@ManyToMany` items: ShopItem[]

* ShopItem
	* id: number
	* name: string
	* description: string
	* price: number
    * `@ManyToOne` type: ShopItemType
	* `@ManyToMany` tags: ShopItemTag[]

* User
	* `@OneToMany` inventory: UserInventoryItem[]

* UserInventoryItem
    * timestamp: Date
    * item: ShopItem
    * `@ManyToOne` user: User

It would then be easier for the API to search for certain tags without the item type, and vice versa.
